CREATE TABLE product (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    reference_no BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    product_type VARCHAR(50) NOT NULL,
    price DECIMAL(19,4) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL,
    updated_by BIGINT NOT NULL,
    active TINYINT(1) NOT NULL DEFAULT 1
   );